### ISSUE TITLE
_sortPathConstraintAttachment  Invalid value: Not in range 0..12

### ISSUE THREAD

**Issue by xvrh** [bp74/StageXL_Spine#3]
Hello Bernhard,
I have an error with a spine here https://github.com/xavierhainaux/spine_dragon (web/main.dart)

In Dartium, it produces this error:

```
Uncaught Unhandled exception:
RangeError (index): Invalid value: Not in range 0..12, inclusive: 13
#0      List.[] (dart:core-patch/growable_array.dart:151)
#1      Skeleton._sortPathConstraintAttachment (package:stagexl_spine/src/skeleton.dart:233:32)
#2      Skeleton._sortPathConstraint (package:stagexl_spine/src/skeleton.dart:181:7)
#3      Skeleton.updateCache (package:stagexl_spine/src/skeleton.dart:134:11)
#4      new Skeleton (package:stagexl_spine/src/skeleton.dart:91:5)
#5      new SkeletonDisplayObject (package:stagexl_spine/src/stagexl/skeleton_display_object.dart:18:24)
#6      new SkeletonAnimation (package:stagexl_spine/src/stagexl/skeleton_animation.dart:10:9)
#7      main (http://localhost:56585/main.dart:30:37)
<asynchronous suspension>
```

The weirdest things is that when compiled to javascript WITH this options ("--trust-type-annotations", "--trust-primitives") it works !!!

Do you have any idea what might be happening here?

**Comment by bp74** [comment]
Oh that's interesting. It probably works in JavaScript just because there are no range checks on arrays.

**Comment by bp74** [comment]
It looks like that the "reta" skin has less attachment than the "lava" skin. Shouldn't both skins have the same number of attachments?

lava
[{aile_d: companions/lava_aile_d, aile_d_blur: companions/lava_aile_d_blur}, 
 {aile_g: companions/lava_aile_g, aile_g_blur: companions/lava_aile_g_blur}, 
 {b_corne_g: companions/lava_corne_g}, 
 {queue: companions/lava_queue}, 
 {pattes_arrieres: companions/lava_pattes_arrieres}, 
 {patte_avant_g: companions/lava_patte_avant_g}, 
 {body: companions/lava_body}, 
 {eyes_open: companions/lava_eye_close, eyes_close: companions/lava_eye_close}, 
 {patte_avant_d: companions/lava_patte_avant_d}, 
 {corne_d_skin: companions/lava_corne_d}, 
 {nez: companions/lava_nez}, 
 {sourcil_g: companions/lava_sourcil_g}, 
 {sourcil_d: companions/lava_sourcil_d}, 
 **null, 
 {deco: companions/lava_moustaches}]**
 
reta
[{aile_d: companions/aile_d, aile_d_blur: companions/aile_d_blur}, 
 {aile_g: companions/aile_g, aile_g_blur: companions/aile_g_blur},
 {b_corne_g: companions/corne_g},
 {queue: companions/queue},
 {pattes_arrieres: companions/pattes_arrieres},
 {patte_avant_g: companions/patte_avant_g},
 {body: companions/body},
 {eyes_close: companions/eye_close_d, eyes_open: companions/eye_open},
 {patte_avant_d: companions/patte_avant_d},
 {corne_d_skin: companions/corne_d},
 {nez: companions/nez},
 {sourcil_g: companions/sourcil_g},
 {sourcil_d: companions/sourcil_d}]

**Comment by bp74** [comment]
There are also a lot of warnings when you export the spine file:

![image](https://user-images.githubusercontent.com/1810450/32135826-997bdfa6-bc05-11e7-9d69-25d0685d0587.png)

**Comment by xvrh** [comment]
Hi Bernhard,
Thank you for taking a look! Your explanation makes sense. 
I will check with our graphic designers to fix the file.

Sorry for the disturbance :-)
